### ISSUE TITLE
Browser

### ISSUE THREAD

**Issue by pevex** [ni2k10/IOTA-Encrypted-Seed-Generator#1]
does it matter which browser I run this in?

**Comment by ignorum23** [comment]
I used chrome and firefox, worked fine there

**Comment by ni2k10** [comment]
Yes, as @ignorum23  has stated. you can use any browser @pevex, I would not recommend using outdated browsers however. you would be best using Firefox or Chrome, something a bit more secure.

also, if you want to be extra safe, disconnect your internet connection whilst generating and nobody can watch as you do it.
